### PR TITLE
Bump version: 0.1.5 → 0.4.0

### PR DESCRIPTION
**Pull request by pcppcp**
should be merged after
https://github.com/raiden-network/raiden-contracts/pull/279

### CODE REVIEW

**Comment by LefterisJP** [comment]
Hmmm ... why bump from 0.1.5 to 0.4.0?

**Comment by pcppcp** [comment]
have no idea LOL, looking into it

**Comment by pcppcp** [comment]
hm, should I make it 0.1.6? I thought the versions should be in sync, at least for minor releases.

**Comment by pcppcp** [comment]
closing this now, will bump patch to 0.1.6

**Comment by LefterisJP** [comment]
Versions of raiden contracts and libs? No, not needed to be in sync. 0.1.6 is fine.

**Pull request closed without merging**
